[package]
name = "hdfrest"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A HDF REST client"
homepage = "https://github.com/davefol/hdfrest"
readme = "README.md"
keywords = ["hdf5", "hdf"]

[dependencies]
