[package]
name = "hdfrest"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A HDF REST client"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
